### ISSUE TITLE
ID returned null

### ISSUE THREAD

**Issue by VickyS08** [rsmithlal/ClimateDataRescue#9]
![screen shot 2016-05-25 at 3 33 21 pm](https://cloud.githubusercontent.com/assets/18540289/15553656/0ab7b96e-228e-11e6-896a-d0ba2d0d6e59.png)

see also screen capture

**Comment by rsmithlal** [comment]
Please include more than a screenshot of just the error message in the future, try to provide some context as well. Also, please indicate the date and time that the error occured so I can go back through the logs to find it. It may be better to just do a whole screen capture using cmd + shift + 3 when you get an error, so that will include your computer's clock too.

**Comment by rsmithlal** [comment]
The new datetime picker should take care of this one. I believe that it was related to an incorrect time format for manual entry on safari.
